### ISSUE TITLE
List past talks with links to slides on the homepage

### ISSUE THREAD

**Issue by keriati** [viennajs/viennajs.org#1]
Hello guys. I noticed two things about viennajs lately:
- Some topics are just repeating over and over again
- It is kind of hard to find the agenda and the presentation slides from few months old talks.

My idea is to put the agenda and the slides from past talks on viennajs.org so people can find interesting (and not so interesting) talks again and download the slides. This way people can see what themes where covered in the past and choose different themes for the next meetup or cover some other part of it.
Maybe there is on meetup.com some option for this, but i couldn't find it sadly.

I can help creating the code for this.
I would also help taking care of collecting the slides (or urls) after the meetups and update viennajs.org with it.

I don't think we need some awesome design for this at the start, but i could ask some friend to  make something that looks nice.

Please give me some feedback :)

**Comment by thomasfr** [comment]
Hi @keriati 

Thanks for taking the time and creating our first issue! :dancers: 

Great idea. This is exactly what i wanted to do. I also want to add the possibility to propose talks for an upcoming meetup with the possibility for others to vote on talks, so the organizer of the meetup can use this as a guideline when creating the agenda for the meetup.

I would really appreciate your help on this.
I also think that we do not need an awesome design at the beginning.

**Comment by franzenzenhofer** [comment]
great idea and thx. for the help.

after the functionality is done, someone from my company f19n.com can do
the css / design work.  (but only after the functionality and the functinal
HTML exists, i always work design last.

lg
franz

**Comment by mraaroncruz** [comment]
I’ve got an instance of locomotivecms running on heroku and I could set up a site with pages and content types for speakers, talks, etc. very easily.
We could even theme it with http://www.blacktie.co/category/themes/ so no one at anyone’s company have to do anything.
I could throw up something to start with this weekend.

Someone else needs to be in charge of content/images though.

@keriati what are some topics you would find more interesting than what you have been hearing?

**Comment by keriati** [comment]
Hey guys,

I'm happy that you like the idea. I don't know if we need here a cms, as the functionality seems faily simple. Actually we could get away without a database if we use some external service for the voting part and put it in with Javascript (yeah) or iframe :). So the github page could be enough with some simple html and some tricks.

What do you think?
